#server:
#  port: 8081
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/alumni_website?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 629000
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alumni_website?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    url: jdbc:mysql://47.120.8.6:3306/book_store?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #    username: book_store
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  configuration:
    #    打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl